name: swing_ai_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - tensorflow=2.15.0
  - numpy=1.26.4
  - pandas=2.2.1
  - scikit-learn=1.4.1
  - matplotlib=3.8.3
  - jupyterlab=4.1.2
  - pip:
    - opencv-python==4.9.0.80
    - tflite-runtime==2.15.0
    - tqdm==4.66.2 